"""
FINTRAC EFT Report (EFTR) XML Generator.

Produces a structured XML file aligned with FINTRAC's EFT reporting schema
for manual upload to the F2R (FINTRAC to Reporting Entity) portal.
Future path: replace download + manual upload with direct F2R API call.
"""

from datetime import datetime, timezone


def generate_eftr_xml(report_data: dict, submission_id: str) -> tuple[str, str]:
    """
    Build FINTRAC-format XML from the submission's report_data dict.
    Returns (xml_string, filename).
    """
    txn_id = report_data.get("transaction_id", "UNKNOWN")
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y%m%d")
    report_ref = f"EFTR-{date_str}-{txn_id}"
    filename = f"EFTR_{txn_id}_{now.strftime('%Y%m%d_%H%M%S')}.xml"
    amend_block = ""
    if report_data.get("amendment_of_ref"):
        amend_block = (
            f"    <AmendedReportReference>"
            f"{_esc(report_data['amendment_of_ref'])}"
            f"</AmendedReportReference>\n"
            f"    <AmendmentReason>"
            f"{_esc(report_data.get('amendment_reason', ''))}"
            f"</AmendmentReason>\n"
        )

    fx_block = ""
    if report_data.get("cad_conversion_rate"):
        fx_block = (
            f"    <FXConversionRate>"
            f"{report_data['cad_conversion_rate']}"
            f"</FXConversionRate>\n"
        )

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!--\n"
        "  FINTRAC Electronic Funds Transfer Report (EFTR)\n"
        "  Generated by: EFTR Regulatory Assurance Platform\n"
        f"  Submission ID : {submission_id}\n"
        f"  Generated at  : {now.isoformat()}\n"
        "\n"
        "  ACTION REQUIRED:\n"
        "    1. Review all [REQUIRED: ...] placeholders below and replace with actual values.\n"
        "    2. Log in to the FINTRAC F2R portal at https://f2r.fintrac-canafe.gc.ca\n"
        "    3. Upload this file via the Batch Upload function.\n"
        "    4. Record the portal reference number in the platform.\n"
        "-->\n"
        '<EFTReport xmlns="http://www.fintrac-canafe.gc.ca/schema/eftr/2.0"\n'
        '           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
        f'           submissionId="{submission_id}"\n'
        f'           generatedAt="{now.isoformat()}">\n'
        "\n"
        "  <!-- ── Reporting Entity ───────────────────────────────────────── -->\n"
        "  <ReportingEntity>\n"
        f"    <ReportingEntityNumber>{_esc(report_data.get('reporting_entity_number', '[REQUIRED: Your FINTRAC Reporting Entity Number]'))}</ReportingEntityNumber>\n"
        f"    <ReportingEntityName>{_esc(report_data.get('reporting_entity_name', '[REQUIRED: Institution Legal Name]'))}</ReportingEntityName>\n"
        f"    <ReportingEntityType>{_esc(report_data.get('reporting_entity_type', 'BANK'))}</ReportingEntityType>\n"
        f"    <ContactName>{_esc(report_data.get('contact_name', '[REQUIRED: Compliance Officer Full Name]'))}</ContactName>\n"
        f"    <ContactPhone>{_esc(report_data.get('contact_phone', '[REQUIRED: Contact Phone Number]'))}</ContactPhone>\n"
        f"    <ContactEmail>{_esc(report_data.get('contact_email', '[REQUIRED: Contact Email Address]'))}</ContactEmail>\n"
        "  </ReportingEntity>\n"
        "\n"
        "  <!-- ── EFT Transaction ────────────────────────────────────────── -->\n"
        "  <EFTTransaction>\n"
        f"    <ReportReference>{report_ref}</ReportReference>\n"
        f"    <TransactionDate>{report_data.get('transaction_date') or report_data.get('value_date', '[REQUIRED: YYYY-MM-DD]')}</TransactionDate>\n"
        f"    <SettlementDate>{report_data.get('settlement_date', '')}</SettlementDate>\n"
        f"    <Direction>{report_data.get('direction', '[REQUIRED: INITIATION or RECEIPT]')}</Direction>\n"
        f"    <Amount>{report_data.get('amount', '[REQUIRED: Amount]')}</Amount>\n"
        f"    <Currency>{report_data.get('currency_code', 'CAD')}</Currency>\n"
        f"    <CADEquivalentAmount>{report_data.get('cad_amount', '[REQUIRED: CAD Equivalent]')}</CADEquivalentAmount>\n"
        f"{fx_block}"
        f"    <TransactionType>{report_data.get('transaction_type', 'EFT')}</TransactionType>\n"
        "\n"
        "    <!-- ── Conductor / Originator ──────────────────────────────── -->\n"
        "    <Conductor>\n"
        f"      <Name>{_esc(report_data.get('originator_name', '[REQUIRED: Originator Full Name]'))}</Name>\n"
        f"      <Address>{_esc(report_data.get('originator_address', '[REQUIRED: Originator Address]'))}</Address>\n"
        f"      <AccountNumber>{_esc(report_data.get('originator_account', '[REQUIRED: Originator Account]'))}</AccountNumber>\n"
        "    </Conductor>\n"
        "\n"
        "    <!-- ── Beneficiary ─────────────────────────────────────────── -->\n"
        "    <Beneficiary>\n"
        f"      <Name>{_esc(report_data.get('beneficiary_name', '[REQUIRED: Beneficiary Full Name]'))}</Name>\n"
        f"      <Address>{_esc(report_data.get('beneficiary_address', '[REQUIRED: Beneficiary Address]'))}</Address>\n"
        f"      <AccountNumber>{_esc(report_data.get('beneficiary_account', '[REQUIRED: Beneficiary Account]'))}</AccountNumber>\n"
        f"      <InstitutionName>{_esc(report_data.get('beneficiary_institution', ''))}</InstitutionName>\n"
        f"      <CountryCode>{report_data.get('beneficiary_country', '')}</CountryCode>\n"
        "    </Beneficiary>\n"
        "\n"
        f"    {'<CounterpartyID>' + _esc(report_data['counterparty_id']) + '</CounterpartyID>' if report_data.get('counterparty_id') else '<!-- CounterpartyID not available -->'}\n"
        "  </EFTTransaction>\n"
        "\n"
        "  <!-- ── Filing Metadata ────────────────────────────────────────── -->\n"
        "  <FilingMetadata>\n"
        f"    <SubmittedBy>{_esc(report_data.get('submitted_by', ''))}</SubmittedBy>\n"
        f"    <ApprovedBy>{_esc(report_data.get('approved_by', ''))}</ApprovedBy>\n"
        f"    <FilingDate>{report_data.get('filing_date', now.strftime('%Y-%m-%d'))}</FilingDate>\n"
        f"    <Remarks>{_esc(report_data.get('remarks', ''))}</Remarks>\n"
        f"{amend_block}"
        "  </FilingMetadata>\n"
        "\n"
        "</EFTReport>\n"
    )

    return xml, filename


def _esc(value: object) -> str:
    """Escape XML special characters."""
    if value is None:
        return ""
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )
